Repository kobylynskyi/graphql-java-codegen, pull requests merged in 2020-05, with the labels that each got.

#137 Add missing backtick to README
  plugins/gradle/README.md
Labels: documentation

#140 Fix request serialization for collections #138
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionToRequestDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/InputDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/TypeDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/DataModelFields.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLRequestSerializer.java
  src/main/resources/templates/javaClassGraphqlType.ftl
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLRequestSerializerTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/UpdateIssueInput.java
  src/test/resources/expected-classes/request/AcceptTopicSuggestionInput.java.txt
Labels: bug

#151 Introduce config to define parent interfaces for Query/Mutation/Subscription apis #135
  plugins/gradle/README.md
  plugins/gradle/example-server/build.gradle
  plugins/gradle/example-server/src/main/java/io/github/kobylynskyi/product/graphql/resolvers/MutationsResolver.java
  plugins/gradle/example-server/src/main/java/io/github/kobylynskyi/product/graphql/resolvers/QueriesResolver.java
  plugins/gradle/graphql-java-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphQLCodegenGradleTask.java
  plugins/gradle/graphql-java-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/ParentInterfacesConfig.java
  plugins/maven/README.md
  plugins/maven/example-server/pom.xml
  plugins/maven/example-server/src/main/java/io/github/kobylynskyi/product/graphql/resolvers/MutationsResolver.java
  plugins/maven/example-server/src/main/java/io/github/kobylynskyi/product/graphql/resolvers/QueriesResolver.java
  plugins/maven/graphql-java-codegen-maven-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/GraphQLCodegenMojo.java
  plugins/maven/graphql-java-codegen-maven-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/ParentInterfacesConfig.java
  plugins/sbt/src/main/scala/io/github/kobylynskyi/graphql/codegen/GraphQLCodegenSbtPlugin.scala
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegen.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionsToResolverDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/GraphQLCodegenConfiguration.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfig.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfigConstants.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingContext.java
  src/main/resources/templates/javaClassGraphqlInterface.ftl
  src/main/resources/templates/javaClassGraphqlOperations.ftl
  src/main/resources/templates/javaClassGraphqlType.ftl
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenParentInterfacesTest.java
  src/test/resources/expected-classes/CommentDeletedEvent.java.txt
  src/test/resources/expected-classes/Commit.java.txt
  src/test/resources/expected-classes/Commit_noParametrizedFields.java.txt
  src/test/resources/expected-classes/Commit_noValidationAnnotation.java.txt
  src/test/resources/expected-classes/GithubCommitTO.java.txt
  src/test/resources/expected-classes/Person.java.txt
  src/test/resources/expected-classes/Person1.java.txt
  src/test/resources/expected-classes/UnionMember1.java.txt
  src/test/resources/expected-classes/UnionMember2.java.txt
  src/test/resources/expected-classes/deprecated/Event.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/Asset.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/Event.java.txt
  src/test/resources/expected-classes/extend/Asset.java.txt
  src/test/resources/expected-classes/extend/Event.java.txt
  src/test/resources/expected-classes/interfaces/Bar1.java.txt
  src/test/resources/expected-classes/interfaces/Foo1.java.txt
  src/test/resources/expected-classes/parent-interfaces/CreateEventMutation.java.txt
  src/test/resources/expected-classes/parent-interfaces/EventResolver.java.txt
  src/test/resources/expected-classes/parent-interfaces/EventsCreatedSubscription.java.txt
  src/test/resources/expected-classes/parent-interfaces/Mutation.java.txt
  src/test/resources/expected-classes/parent-interfaces/Query.java.txt
  src/test/resources/expected-classes/parent-interfaces/Subscription.java.txt
  src/test/resources/expected-classes/parent-interfaces/VersionQuery.java.txt
Labels: enhancement

#152 feat: Support for enum in unions
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/EnumDefinitionToDataModelMapper.java
  src/main/resources/templates/javaClassGraphqlEnum.ftl
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenUnionWithEnumTest.java
  src/test/resources/expected-classes/enum-union/EnumMember1.java.txt
  src/test/resources/expected-classes/enum-union/EnumMember2.java.txt
  src/test/resources/expected-classes/enum-union/EnumUnion.java.txt
  src/test/resources/schemas/union-with-enum.graphqls
Labels: enhancement

#155 Support of parametrized fields in ResponseProjection #153
  plugins/gradle/README.md
  plugins/gradle/graphql-java-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphQLCodegenGradleTask.java
  plugins/maven/README.md
  plugins/maven/graphql-java-codegen-maven-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/GraphQLCodegenMojo.java
  src/main/java/com/kobylynskyi/graphql/codegen/FreeMarkerTemplatesRegistry.java
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegen.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionToParameterMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/MapperUtils.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/TypeDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/GraphQLCodegenConfiguration.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfig.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfigConstants.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingContext.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/ProjectionParameterDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLParametrizedInput.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLResponseProjection.java
  src/main/resources/templates/javaClassGraphqlParametrizedInput.ftl
  src/main/resources/templates/javaClassGraphqlResponseProjection.ftl
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenRequestTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/MappingConfigTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLRequestSerializerTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/EventPropertyChildParametrizedInput.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/EventPropertyParentParametrizedInput.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/EventPropertyResponseProjection.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/EventResponseProjection.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/IssueResponseProjection.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/UpdateIssuePayloadResponseProjection.java
  src/test/resources/expected-classes/extend/request/AssetResponseProjection.java.txt
  src/test/resources/expected-classes/extend/request/EventResponseProjection.java.txt
  src/test/resources/expected-classes/request/AcceptTopicSuggestionInput.java.txt
  src/test/resources/expected-classes/request/CodeOfConductResponseProjection.java.txt
  src/test/resources/expected-classes/request/EventPropertyChildParametrizedInput.java.txt
  src/test/resources/expected-classes/request/EventPropertyParentParametrizedInput.java.txt
  src/test/resources/expected-classes/request/EventPropertyParentParametrizedInput_withModelSuffix.java.txt
  src/test/resources/expected-classes/request/EventPropertyResponseProjection.java.txt
  src/test/resources/expected-classes/request/EventResponseProjection.java.txt
  src/test/resources/expected-classes/request/EventsByCategoryAndStatusQueryRequest.java.txt
  src/test/resources/expected-classes/request/EventsByCategoryAndStatusQueryRequest_withApiImport.java.txt
  src/test/resources/expected-classes/request/EventsByCategoryAndStatusQueryRequest_withModelSuffix.java.txt
  src/test/resources/expected-classes/request/EventsByIdsQueryRequest.java.txt
  src/test/resources/expected-classes/request/ProductsByCategoryIdAndStatusQueryRequest.java.txt
  src/test/resources/expected-classes/request/ProductsByIdsQueryRequest.java.txt
  src/test/resources/expected-classes/request/UpdateRepositoryMutationRequest.java.txt
  src/test/resources/expected-classes/request/VersionQueryRequest.java.txt
  src/test/resources/schemas/test.graphqls
Labels: enhancement

#156 Externalize codegen options to a separate file
  docs/codegen-options.md
  plugins/gradle/README.md
  plugins/maven/README.md
Labels: documentation, enhancement

#157 Support of HTTP Query String serialization #154
  build.gradle
  src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLRequest.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLRequestSerializer.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLRequestSerializerTest.java
Labels: enhancement

#158 Corrected build.gradle.kts sample
  plugins/gradle/README.md
Labels: documentation
