Repository kobylynskyi/graphql-java-codegen, pull requests merged in 2020-06, with the labels that each got.

#162 Allow extensions-only schema #160
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegen.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedEnumTypeDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedInputObjectTypeDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedInterfaceTypeDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedObjectTypeDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedUnionTypeDefinition.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenExtendTest.java
  src/test/resources/schemas/only-extend-queries.graphqls
Labels: bug

#161 Generate Response class having response data with exact type #159
  docs/codegen-options.md
  plugins/gradle/example-client/build.gradle
  plugins/gradle/example-client/src/main/java/io/github/kobylynskyi/order/external/ProductServiceGraphQLClient.java
  plugins/gradle/graphql-java-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphQLCodegenGradleTask.java
  plugins/maven/example-client/pom.xml
  plugins/maven/example-client/src/main/java/io/github/kobylynskyi/order/external/ProductServiceGraphQLClient.java
  plugins/maven/graphql-java-codegen-maven-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/GraphQLCodegenMojo.java
  src/main/java/com/kobylynskyi/graphql/codegen/FreeMarkerTemplatesRegistry.java
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegen.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionToRequestDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/InputDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/MapperUtils.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/RequestResponseDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/TypeDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/DataModelFields.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/GraphQLCodegenConfiguration.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfig.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfigConstants.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingContext.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLError.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLErrorSourceLocation.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLResult.java
  src/main/resources/templates/javaClassGraphqlResponse.ftl
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenExtendTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenRequestTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenResponseTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/MappingConfigTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLResultTest.java
  src/test/resources/expected-classes/response/EventsByCategoryAndStatusQueryResponse.java.txt
  src/test/resources/expected-classes/response/EventsByIdsQueryResponse.java.txt
  src/test/resources/expected-classes/response/VersionQueryResponse.java.txt
Labels: enhancement

#168 Model classes should implement java.io.Serializable #167
  build.gradle
  src/main/resources/templates/javaClassGraphqlType.ftl
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenFieldsResolversTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/TestUtils.java
  src/test/resources/expected-classes/CommentDeletedEvent.java.txt
  src/test/resources/expected-classes/Commit.java.txt
  src/test/resources/expected-classes/Commit_noParametrizedFields.java.txt
  src/test/resources/expected-classes/Commit_noValidationAnnotation.java.txt
  src/test/resources/expected-classes/Event.java.txt
  src/test/resources/expected-classes/EventProperty.java.txt
  src/test/resources/expected-classes/EventPropertyTO_toString.java.txt
  src/test/resources/expected-classes/EventPropertyTO_withEqualsAndHashCode.java.txt
  src/test/resources/expected-classes/Event_noBuilder.java.txt
  src/test/resources/expected-classes/GithubAcceptTopicSuggestionInputTO.java.txt
  src/test/resources/expected-classes/GithubAcceptTopicSuggestionPayloadTO.java.txt
  src/test/resources/expected-classes/GithubCommitTO.java.txt
  src/test/resources/expected-classes/Person.java.txt
  src/test/resources/expected-classes/Person1.java.txt
  src/test/resources/expected-classes/UnionMember1.java.txt
  src/test/resources/expected-classes/UnionMember2.java.txt
  src/test/resources/expected-classes/defaults/InputWithDefaults.java.txt
  src/test/resources/expected-classes/defaults/InputWithDefaultsTO.java.txt
  src/test/resources/expected-classes/defaults/SomeObject.java.txt
  src/test/resources/expected-classes/defaults/SomeObjectTO.java.txt
  src/test/resources/expected-classes/deprecated/Event.java.txt
  src/test/resources/expected-classes/deprecated/EventInput.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/Asset.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/AssetInput.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/Event.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/EventInput.java.txt
  src/test/resources/expected-classes/extend/Asset.java.txt
  src/test/resources/expected-classes/extend/AssetInput.java.txt
  src/test/resources/expected-classes/extend/Event.java.txt
  src/test/resources/expected-classes/extend/EventInput.java.txt
  src/test/resources/expected-classes/interfaces/Bar1.java.txt
  src/test/resources/expected-classes/interfaces/Foo1.java.txt
  src/test/resources/expected-classes/request/AcceptTopicSuggestionInput.java.txt
Labels: enhancement

#170 Remove deprecated methods #169
  plugins/gradle/graphql-java-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphQLCodegenGradleTask.java
  plugins/maven/graphql-java-codegen-maven-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/GraphQLCodegenMojo.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLRequest.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLRequestSerializer.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLRequestSerializerTest.java
Labels: enhancement

#171 Introduce ApiRootInterfaceStrategy and ApiNamePrefixStrategy #142
  docs/codegen-options.md
  plugins/gradle/graphql-java-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphQLCodegenGradleTask.java
  plugins/maven/graphql-java-codegen-maven-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/GraphQLCodegenMojo.java
  src/main/java/com/kobylynskyi/graphql/codegen/FreeMarkerTemplatesRegistry.java
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegen.java
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenFileCreator.java
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenValidate.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/MapperUtils.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/ApiNamePrefixStrategy.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/ApiRootInterfaceStrategy.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/GraphQLCodegenConfiguration.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfig.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfigConstants.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingContext.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedObjectTypeDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/exception/SchemaValidationException.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/exception/UnableToCreateDirectoryException.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/exception/UnableToCreateFileException.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/exception/UnableToDeleteDirectoryException.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/exception/UnableToLoadFreeMarkerTemplateException.java
  src/main/java/com/kobylynskyi/graphql/codegen/utils/Utils.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenApisTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenValidateTest.java
  src/test/resources/schemas/sub-proj_1/sub-schema1.graphqls
  src/test/resources/schemas/sub-proj_2/sub-schema2.graphqls
Labels: enhancement

#174 Field aliases support for client generator #173
  src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLResponseField.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLResponseProjection.java
  src/main/resources/templates/javaClassGraphqlResponseProjection.ftl
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLRequestSerializerTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/EventPropertyResponseProjection.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/EventResponseProjection.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/IssueResponseProjection.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/UpdateIssuePayloadResponseProjection.java
  src/test/resources/expected-classes/extend/request/AssetResponseProjection.java.txt
  src/test/resources/expected-classes/extend/request/EventResponseProjection.java.txt
  src/test/resources/expected-classes/request/CodeOfConductResponseProjection.java.txt
  src/test/resources/expected-classes/request/EventPropertyResponseProjection.java.txt
  src/test/resources/expected-classes/request/EventResponseProjection.java.txt
Labels: enhancement

#175 Add generation of immutable models
  docs/codegen-options.md
  plugins/gradle/graphql-java-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphQLCodegenGradleTask.java
  plugins/maven/graphql-java-codegen-maven-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/GraphQLCodegenMojo.java
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegen.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/InputDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/TypeDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/DataModelFields.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/GraphQLCodegenConfiguration.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfig.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfigConstants.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingContext.java
  src/main/resources/templates/javaClassGraphqlType.ftl
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenImmutableTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/MappingConfigTest.java
  src/test/resources/expected-classes/immutable/Event.java.txt
Labels: enhancement

#186 Use java.util.List for GQL lists
  plugins/gradle/example-client/src/main/java/io/github/kobylynskyi/order/external/ProductServiceGraphQLClient.java
  plugins/gradle/example-client/src/main/java/io/github/kobylynskyi/order/graphql/resolvers/QueriesResolver.java
  plugins/gradle/example-server/src/main/java/io/github/kobylynskyi/product/graphql/resolvers/QueriesResolver.java
  plugins/maven/example-client/src/main/java/io/github/kobylynskyi/order/external/ProductServiceGraphQLClient.java
  plugins/maven/example-client/src/main/java/io/github/kobylynskyi/order/graphql/resolvers/QueriesResolver.java
  plugins/maven/example-server/src/main/java/io/github/kobylynskyi/product/graphql/resolvers/QueriesResolver.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/GraphqlTypeToJavaTypeMapper.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenTest.java
  src/test/resources/expected-classes/CommitResolver.java.txt
  src/test/resources/expected-classes/Event.java.txt
  src/test/resources/expected-classes/EventProperty.java.txt
  src/test/resources/expected-classes/EventPropertyTO_toString.java.txt
  src/test/resources/expected-classes/EventPropertyTO_withEqualsAndHashCode.java.txt
  src/test/resources/expected-classes/Event_noBuilder.java.txt
  src/test/resources/expected-classes/EventsByCategoryAndStatusQueryResolver.java.txt
  src/test/resources/expected-classes/EventsByIdsQueryResolver.java.txt
  src/test/resources/expected-classes/EventsCreatedSubscriptionResolver.java.txt
  src/test/resources/expected-classes/ProductsByCategoryIdAndStatusQueryResolver.java.txt
  src/test/resources/expected-classes/ProductsByIdsQueryResolver.java.txt
  src/test/resources/expected-classes/QueryResolver.java.txt
  src/test/resources/expected-classes/SubscriptionResolver.java.txt
  src/test/resources/expected-classes/defaults/InputWithDefaults.java.txt
  src/test/resources/expected-classes/defaults/InputWithDefaultsTO.java.txt
  src/test/resources/expected-classes/deprecated/EventsQueryResolver.java.txt
  src/test/resources/expected-classes/deprecated/QueryResolver.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/AssetsQueryResolver.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/EventInput.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/EventResolver.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/EventsQueryResolver.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/QueryResolver.java.txt
  src/test/resources/expected-classes/extend/AssetsQueryResolver.java.txt
  src/test/resources/expected-classes/extend/Event.java.txt
  src/test/resources/expected-classes/extend/EventInput.java.txt
  src/test/resources/expected-classes/extend/EventsQueryResolver.java.txt
  src/test/resources/expected-classes/extend/QueryResolver.java.txt
  src/test/resources/expected-classes/immutable/Event.java.txt
  src/test/resources/expected-classes/interfaces/Foo.java.txt
  src/test/resources/expected-classes/interfaces/Foo1.java.txt
  src/test/resources/expected-classes/parent-interfaces/EventResolver.java.txt
  src/test/resources/expected-classes/parent-interfaces/EventsCreatedSubscriptionResolver.java.txt
  src/test/resources/expected-classes/parent-interfaces/QueryResolver.java.txt
  src/test/resources/expected-classes/parent-interfaces/SubscriptionResolver.java.txt
  src/test/resources/expected-classes/request/EventsByIdsQueryRequest.java.txt
  src/test/resources/expected-classes/request/ProductsByIdsQueryRequest.java.txt
  src/test/resources/expected-classes/response/EventsByCategoryAndStatusQueryResponse.java.txt
  src/test/resources/expected-classes/response/EventsByIdsQueryResponse.java.txt
Labels: breaking change, bug

#179 Fix a case when List NonNullType has a default value #177
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/DefaultValueMapper.java
  src/test/resources/expected-classes/defaults/InputWithDefaults.java.txt
  src/test/resources/expected-classes/defaults/InputWithDefaultsTO.java.txt
  src/test/resources/schemas/defaults.graphqls
Labels: bug
