Repository kobylynskyi/graphql-java-codegen, pull requests merged in 2020-04, with the labels that each got.

#34 Gather library and maven/gradle plugins in a single repo
  .circleci/config.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  build.gradle
  plugins/graphql-java-codegen-gradle-plugin/README.md
  plugins/graphql-java-codegen-gradle-plugin/build.gradle
  plugins/graphql-java-codegen-gradle-plugin/gradle/wrapper/gradle-wrapper.jar
  plugins/graphql-java-codegen-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
  plugins/graphql-java-codegen-gradle-plugin/gradlew
  plugins/graphql-java-codegen-gradle-plugin/gradlew.bat
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin-example/build.gradle
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin-example/src/main/java/io/github/kobylynskyi/bikeshop/Application.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin-example/src/main/java/io/github/kobylynskyi/bikeshop/graphql/GraphQLController.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin-example/src/main/java/io/github/kobylynskyi/bikeshop/graphql/config/GraphQLConfiguration.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin-example/src/main/java/io/github/kobylynskyi/bikeshop/graphql/mappers/BikeMapper.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin-example/src/main/java/io/github/kobylynskyi/bikeshop/graphql/resolvers/MutationsResolver.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin-example/src/main/java/io/github/kobylynskyi/bikeshop/graphql/resolvers/QueriesResolver.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin-example/src/main/java/io/github/kobylynskyi/bikeshop/model/Bike.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin-example/src/main/java/io/github/kobylynskyi/bikeshop/model/BikeType.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin-example/src/main/java/io/github/kobylynskyi/bikeshop/repository/BikeRepository.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin-example/src/main/java/io/github/kobylynskyi/bikeshop/service/BikeService.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin-example/src/main/resources/schema.graphqls
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin/build.gradle
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphqlCodegenGradlePlugin.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphqlCodegenGradleTask.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphqlCodegenValidateGradleTask.java
  plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin/src/main/resources/META-INF/gradle-plugins/io.github.kobylynskyi.graphql.codegen.properties
  plugins/graphql-java-codegen-gradle-plugin/settings.gradle
  plugins/graphql-java-codegen-maven-plugin/README.md
  plugins/graphql-java-codegen-maven-plugin/example/pom.xml
  plugins/graphql-java-codegen-maven-plugin/example/src/main/java/io/github/kobylynskyi/bikeshop/Application.java
  plugins/graphql-java-codegen-maven-plugin/example/src/main/java/io/github/kobylynskyi/bikeshop/graphql/GraphQLController.java
  plugins/graphql-java-codegen-maven-plugin/example/src/main/java/io/github/kobylynskyi/bikeshop/graphql/config/GraphQLConfiguration.java
  plugins/graphql-java-codegen-maven-plugin/example/src/main/java/io/github/kobylynskyi/bikeshop/graphql/mappers/BikeMapper.java
  plugins/graphql-java-codegen-maven-plugin/example/src/main/java/io/github/kobylynskyi/bikeshop/graphql/resolvers/MutationsResolver.java
  plugins/graphql-java-codegen-maven-plugin/example/src/main/java/io/github/kobylynskyi/bikeshop/graphql/resolvers/QueriesResolver.java
  plugins/graphql-java-codegen-maven-plugin/example/src/main/java/io/github/kobylynskyi/bikeshop/model/Bike.java
  plugins/graphql-java-codegen-maven-plugin/example/src/main/java/io/github/kobylynskyi/bikeshop/model/BikeType.java
  plugins/graphql-java-codegen-maven-plugin/example/src/main/java/io/github/kobylynskyi/bikeshop/repository/BikeRepository.java
  plugins/graphql-java-codegen-maven-plugin/example/src/main/java/io/github/kobylynskyi/bikeshop/service/BikeService.java
  plugins/graphql-java-codegen-maven-plugin/example/src/main/resources/schema.graphqls
  plugins/graphql-java-codegen-maven-plugin/pom.xml
  plugins/graphql-java-codegen-maven-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/GraphqlCodegenMojo.java
Labels: enhancement

#53 Introduce codegen for client code - Part 1. #37
  src/main/java/com/kobylynskyi/graphql/codegen/FreeMarkerTemplatesRegistry.java
  src/main/java/com/kobylynskyi/graphql/codegen/GraphqlCodegen.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/EnumDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionToParameterMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionToRequestDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/GraphqlTypeToJavaTypeMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/InputValueDefinitionToParameterMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/InterfaceDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/MapperUtils.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/TypeDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/DataModelFields.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/DefaultMappingConfigValues.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfig.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/ProjectionParameterDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/request/GraphQLOperationRequest.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/request/GraphQLRequest.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/request/GraphQLRequestSerializer.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/request/GraphQLResponseProjection.java
  src/main/resources/templates/javaClassGraphqlEnum.ftl
  src/main/resources/templates/javaClassGraphqlRequest.ftl
  src/main/resources/templates/javaClassGraphqlResponseProjection.ftl
  src/main/resources/templates/javaClassGraphqlType.ftl
  src/test/java/com/kobylynskyi/graphql/codegen/GraphqlCodegenRequestTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphqlCodegenTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/MappingConfigTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/request/GraphQLRequestSerializerTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/request/data/EventPropertyResponseProjection.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/request/data/EventResponseProjection.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/request/data/EventsByCategoryAndStatusQueryRequest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/request/data/EventsByIdsQueryRequest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/request/data/IssueResponseProjection.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/request/data/Status.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/request/data/UpdateIssueInput.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/request/data/UpdateIssueMutationRequest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/request/data/UpdateIssuePayloadResponseProjection.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/request/data/VersionQueryRequest.java
  src/test/resources/expected-classes/EventStatus.java.txt
  src/test/resources/expected-classes/EventsByIdsQuery.java.txt
  src/test/resources/expected-classes/MyEnum.java.txt
  src/test/resources/expected-classes/Query.java.txt
  src/test/resources/expected-classes/request/AcceptTopicSuggestionInput.java.txt
  src/test/resources/expected-classes/request/CodeOfConductResponseProjection.java.txt
  src/test/resources/expected-classes/request/EventPropertyResponseProjection.java.txt
  src/test/resources/expected-classes/request/EventResponseProjection.java.txt
  src/test/resources/expected-classes/request/EventStatusTO.java.txt
  src/test/resources/expected-classes/request/EventsByCategoryAndStatusQueryRequest.java.txt
  src/test/resources/expected-classes/request/EventsByCategoryAndStatusQueryRequest_withModelSuffix.java.txt
  src/test/resources/expected-classes/request/EventsByIdsQueryRequest.java.txt
  src/test/resources/expected-classes/request/UpdateRepositoryMutationRequest.java.txt
  src/test/resources/expected-classes/request/VersionQueryRequest.java.txt
  src/test/resources/expected-classes/request/graphql-query/eventsByCategoryAndStatusQuery.txt
  src/test/resources/expected-classes/request/graphql-query/eventsByIdsQuery.txt
  src/test/resources/expected-classes/request/graphql-query/updateIssueMutation.txt
  src/test/resources/expected-classes/request/graphql-query/versionQuery.txt
  src/test/resources/schemas/test.graphqls
Labels: enhancement

#54 Generate Builder for model classes #10
  plugins/gradle/README.md
  plugins/gradle/graphql-java-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphqlCodegenGradleTask.java
  plugins/maven/README.md
  plugins/maven/graphql-java-codegen-maven-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/GraphqlCodegenMojo.java
  src/main/java/com/kobylynskyi/graphql/codegen/GraphqlCodegen.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionToRequestDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/InputDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/TypeDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/DataModelFields.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/DefaultMappingConfigValues.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfig.java
  src/main/resources/templates/javaClassGraphqlType.ftl
  src/test/java/com/kobylynskyi/graphql/codegen/GraphqlCodegenTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/MappingConfigTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/request/data/UpdateIssueInput.java
  src/test/resources/expected-classes/AcceptTopicSuggestionPayload.java.txt
  src/test/resources/expected-classes/Commit.java.txt
  src/test/resources/expected-classes/Commit_noParametrizedFields.java.txt
  src/test/resources/expected-classes/Commit_noValidationAnnotation.java.txt
  src/test/resources/expected-classes/Event.java.txt
  src/test/resources/expected-classes/EventProperty.java.txt
  src/test/resources/expected-classes/EventPropertyTO_withEqualsAndHashCode.java.txt
  src/test/resources/expected-classes/Event_noBuilder.java.txt
  src/test/resources/expected-classes/GithubAcceptTopicSuggestionInputTO.java.txt
  src/test/resources/expected-classes/GithubCommitTO.java.txt
  src/test/resources/expected-classes/InputWithDefaults.java.txt
  src/test/resources/expected-classes/SomeObject.java.txt
  src/test/resources/expected-classes/UnionMember1.java.txt
  src/test/resources/expected-classes/UnionMember2.java.txt
  src/test/resources/expected-classes/request/AcceptTopicSuggestionInput.java.txt
Labels: enhancement

#65 Extend and enhance README.md #37
  plugins/gradle/README.md
  plugins/maven/README.md
Labels: documentation, enhancement

#78 Add example client code using RestAssured, enhance README.md #74
  plugins/gradle/README.md
  plugins/gradle/example-client/build.gradle
  plugins/gradle/example-client/src/test/java/io/github/kobylynskyi/order/service/CreateProductIntegrationTest.java
  plugins/maven/README.md
  plugins/maven/example-client/pom.xml
  plugins/maven/example-client/src/test/java/io/github/kobylynskyi/order/service/CreateProductIntegrationTest.java
Labels: documentation, enhancement

#89 Add test with empty types and extensions #81
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenExtendTest.java
  src/test/resources/schemas/empty-types-with-extend.graphqls
Labels: enhancement

#90 Add more mapping configs for extensions resolvers #81
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegen.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionToParameterMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionsToResolverDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/InterfaceDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/DefaultMappingConfigValues.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfig.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedInterfaceTypeDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedObjectTypeDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/FieldDefinitionFromExtension.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenExtendTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenFieldsResolversTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/MappingConfigTest.java
  src/test/resources/expected-classes/CommentDeletedEvent.java.txt
  src/test/resources/expected-classes/CommentDeletedEventResolver.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/Asset.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/AssetInput.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/AssetsQuery.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/CreateAssetMutation.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/CreateEventMutation.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/Event.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/EventInput.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/EventResolver.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/EventsQuery.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/Mutation.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/Node.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/NodeResolver.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/PinnableItem.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/Query.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/Status.java.txt
Labels: enhancement

#95 Generate Builder for Request classes #67
  src/main/resources/templates/javaClassGraphqlRequest.ftl
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLRequestSerializerTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/EventsByCategoryAndStatusQueryRequest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/EventsByIdsQueryRequest.java
  src/test/java/com/kobylynskyi/graphql/codegen/model/graphql/data/VersionQueryRequest.java
  src/test/resources/expected-classes/request/EventsByCategoryAndStatusQueryRequest.java.txt
  src/test/resources/expected-classes/request/EventsByCategoryAndStatusQueryRequest_withModelSuffix.java.txt
  src/test/resources/expected-classes/request/EventsByIdsQueryRequest.java.txt
  src/test/resources/expected-classes/request/UpdateRepositoryMutationRequest.java.txt
  src/test/resources/expected-classes/request/VersionQueryRequest.java.txt
Labels: enhancement

#100 Extend default SchemaFinder include pattern config #97
  plugins/gradle/README.md
  plugins/maven/README.md
  src/main/java/com/kobylynskyi/graphql/codegen/supplier/SchemaFinder.java
  src/test/java/com/kobylynskyi/graphql/codegen/supplier/SchemaFinderTest.java
Labels: enhancement

#99 Add javadoc to all generated classes #84
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegen.java
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLDocumentParser.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/EnumDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionToParameterMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionToRequestDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionsToResolverDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/InputDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/InterfaceDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/TypeDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/UnionDefinitionToDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/DataModelFields.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/EnumValueDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/FieldResolverDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/OperationDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/ParameterDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedFieldDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedInterfaceTypeDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/ExtendedObjectTypeDefinition.java
  src/main/java/com/kobylynskyi/graphql/codegen/model/definitions/FieldDefinitionFromExtension.java
  src/main/resources/templates/javaClassGraphqlEnum.ftl
  src/main/resources/templates/javaClassGraphqlInterface.ftl
  src/main/resources/templates/javaClassGraphqlOperations.ftl
  src/main/resources/templates/javaClassGraphqlRequest.ftl
  src/main/resources/templates/javaClassGraphqlResponseProjection.ftl
  src/main/resources/templates/javaClassGraphqlType.ftl
  src/main/resources/templates/javaClassGraphqlUnion.ftl
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenTest.java
  src/test/resources/expected-classes/CreateEventMutation.java.txt
  src/test/resources/expected-classes/Event.java.txt
  src/test/resources/expected-classes/EventByIdQuery.java.txt
  src/test/resources/expected-classes/EventProperty.java.txt
  src/test/resources/expected-classes/EventPropertyTO_toString.java.txt
  src/test/resources/expected-classes/EventPropertyTO_withEqualsAndHashCode.java.txt
  src/test/resources/expected-classes/EventStatus.java.txt
  src/test/resources/expected-classes/Event_noBuilder.java.txt
  src/test/resources/expected-classes/EventsByCategoryAndStatusQuery.java.txt
  src/test/resources/expected-classes/EventsByIdsQuery.java.txt
  src/test/resources/expected-classes/EventsCreatedSubscription.java.txt
  src/test/resources/expected-classes/InputWithDefaults.java.txt
  src/test/resources/expected-classes/Mutation.java.txt
  src/test/resources/expected-classes/Query.java.txt
  src/test/resources/expected-classes/Subscription.java.txt
  src/test/resources/expected-classes/VersionQuery.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/EventResolver.java.txt
  src/test/resources/expected-classes/extend/Event.java.txt
  src/test/resources/expected-classes/extend/request/AssetResponseProjection.java.txt
  src/test/resources/expected-classes/extend/request/EventResponseProjection.java.txt
  src/test/resources/expected-classes/request/CodeOfConductResponseProjection.java.txt
  src/test/resources/expected-classes/request/EventPropertyResponseProjection.java.txt
  src/test/resources/expected-classes/request/EventResponseProjection.java.txt
  src/test/resources/expected-classes/request/EventStatusTO.java.txt
  src/test/resources/expected-classes/request/EventsByCategoryAndStatusQueryRequest.java.txt
  src/test/resources/expected-classes/request/EventsByCategoryAndStatusQueryRequest_withModelSuffix.java.txt
  src/test/resources/expected-classes/request/EventsByIdsQueryRequest.java.txt
  src/test/resources/expected-classes/request/VersionQueryRequest.java.txt
  src/test/resources/schemas/empty-types-with-extend.graphqls
  src/test/resources/schemas/extend1.graphqls
  src/test/resources/schemas/extend2.graphqls
  src/test/resources/schemas/test.graphqls
Labels: enhancement

#102 Fix imports if APIs are not being generated #101
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/MapperUtils.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenRequestTest.java
  src/test/resources/expected-classes/request/EventsByCategoryAndStatusQueryRequest_withApiImport.java.txt
Labels: bug

#114 Add Gradle wrapper #111
  .circleci/config.yml
  CONTRIBUTING.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement

#117 Migrate from CircleCI to GitHub Actions #115
  .circleci/config.yml
  .github/workflows/github.yml
  README.md
  plugins/gradle/README.md
  plugins/maven/README.md
  plugins/maven/graphql-java-codegen-maven-plugin/pom.xml
Labels: enhancement

#113 Update dependencies #112
  build.gradle
  plugins/gradle/example-client/build.gradle
  plugins/gradle/example-client/src/main/java/io/github/kobylynskyi/order/external/ProductServiceGraphQLClient.java
  plugins/gradle/example-client/src/main/java/io/github/kobylynskyi/order/graphql/GraphQLController.java
  plugins/gradle/example-client/src/main/java/io/github/kobylynskyi/order/graphql/config/GraphQLConfiguration.java
  plugins/gradle/example-client/src/main/java/io/github/kobylynskyi/order/graphql/resolvers/MutationsResolver.java
  plugins/gradle/example-client/src/main/java/io/github/kobylynskyi/order/graphql/resolvers/QueriesResolver.java
  plugins/gradle/example-client/src/main/resources/application.properties
  plugins/gradle/example-client/src/main/resources/application.yml
  plugins/gradle/example-server/build.gradle
  plugins/gradle/example-server/src/main/java/io/github/kobylynskyi/product/graphql/GraphQLController.java
  plugins/gradle/example-server/src/main/java/io/github/kobylynskyi/product/graphql/config/GraphQLConfiguration.java
  plugins/gradle/example-server/src/main/java/io/github/kobylynskyi/product/graphql/resolvers/MutationsResolver.java
  plugins/gradle/example-server/src/main/java/io/github/kobylynskyi/product/graphql/resolvers/QueriesResolver.java
  plugins/gradle/example-server/src/main/resources/application.properties
  plugins/gradle/example-server/src/main/resources/application.yml
  plugins/gradle/graphql-java-codegen-gradle-plugin/build.gradle
  plugins/maven/example-client/pom.xml
  plugins/maven/example-client/src/main/java/io/github/kobylynskyi/order/external/ProductServiceGraphQLClient.java
  plugins/maven/example-client/src/main/java/io/github/kobylynskyi/order/graphql/GraphQLController.java
  plugins/maven/example-client/src/main/java/io/github/kobylynskyi/order/graphql/config/GraphQLConfiguration.java
  plugins/maven/example-client/src/main/java/io/github/kobylynskyi/order/graphql/resolvers/MutationsResolver.java
  plugins/maven/example-client/src/main/java/io/github/kobylynskyi/order/graphql/resolvers/QueriesResolver.java
  plugins/maven/example-client/src/main/resources/application.properties
  plugins/maven/example-client/src/main/resources/application.yml
  plugins/maven/example-server/pom.xml
  plugins/maven/example-server/src/main/java/io/github/kobylynskyi/product/graphql/GraphQLController.java
  plugins/maven/example-server/src/main/java/io/github/kobylynskyi/product/graphql/config/GraphQLConfiguration.java
  plugins/maven/example-server/src/main/java/io/github/kobylynskyi/product/graphql/resolvers/MutationsResolver.java
  plugins/maven/example-server/src/main/java/io/github/kobylynskyi/product/graphql/resolvers/QueriesResolver.java
  plugins/maven/example-server/src/main/resources/application.properties
  plugins/maven/example-server/src/main/resources/application.yml
Labels: enhancement

#122 Add more options to the sbt plugin
  plugins/sbt/README.md
  plugins/sbt/src/main/scala/io/github/kobylynskyi/graphql/codegen/GraphQLCodegenSbtPlugin.scala
Labels: enhancement

#120 Fix codegen when multiple queries having same name #106
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegen.java
  src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenFileCreator.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionToRequestDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/FieldDefinitionsToResolverDataModelMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/GraphqlTypeToJavaTypeMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/MapperUtils.java
  src/main/java/com/kobylynskyi/graphql/codegen/utils/Utils.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenRequestTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenTest.java
  src/test/resources/expected-classes/AcceptTopicSuggestionPayloadResolver.java.txt
  src/test/resources/expected-classes/CommentDeletedEventResolver.java.txt
  src/test/resources/expected-classes/CommitResolver.java.txt
  src/test/resources/expected-classes/CreateEventMutation.java.txt
  src/test/resources/expected-classes/EventByIdQuery.java.txt
  src/test/resources/expected-classes/EventsByCategoryAndStatusQuery.java.txt
  src/test/resources/expected-classes/EventsByIdsQuery.java.txt
  src/test/resources/expected-classes/EventsCreatedSubscription.java.txt
  src/test/resources/expected-classes/ProductsByCategoryIdAndStatusQuery.java.txt
  src/test/resources/expected-classes/ProductsByIdsQuery.java.txt
  src/test/resources/expected-classes/VersionQuery.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/EventResolver.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/NodeResolver.java.txt
  src/test/resources/expected-classes/extend-with-resolvers/Query.java.txt
  src/test/resources/expected-classes/extend/Query.java.txt
  src/test/resources/expected-classes/request/ProductsByCategoryIdAndStatusQueryRequest.java.txt
  src/test/resources/expected-classes/request/ProductsByIdsQueryRequest.java.txt
  src/test/resources/schemas/empty-types-with-extend.graphqls
  src/test/resources/schemas/queries-same-name.graphqls
Labels: bug

#129 Handle duplicate fields from the type and interface #128
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/TypeDefinitionToDataModelMapper.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenDefaultsTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenExtendTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenExternalConfigTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenFieldsResolversTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenGitHubTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenMultiFilesTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenRequestTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/TestUtils.java
  src/test/resources/expected-classes/Person.java.txt
  src/test/resources/expected-classes/Person1.java.txt
  src/test/resources/schemas/type-interface-duplicate-fields.graphqls
  src/test/resources/schemas/type-interface-duplicate-fields1.graphqls
Labels: bug

#132 Fix enum default value generation when suffix provided #131
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/DefaultValueMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/mapper/InputValueDefinitionToParameterMapper.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenDefaultsTest.java
  src/test/resources/expected-classes/defaults/InputWithDefaults.java.txt
  src/test/resources/expected-classes/defaults/InputWithDefaultsTO.java.txt
  src/test/resources/expected-classes/defaults/MyEnum.java.txt
  src/test/resources/expected-classes/defaults/MyEnumTO.java.txt
  src/test/resources/expected-classes/defaults/SomeObject.java.txt
  src/test/resources/expected-classes/defaults/SomeObjectTO.java.txt
Labels: bug

#133 Gradle readme - fix outputDir data type
  plugins/gradle/README.md
Labels: documentation
