Repository kobylynskyi/graphql-java-codegen, pull requests merged in 2021-03, with the labels that each got.

#588 Scala optimization
  src/main/java/com/kobylynskyi/graphql/codegen/scala/ScalaGraphQLCodegen.java
  src/main/java/com/kobylynskyi/graphql/codegen/scala/ScalaGraphQLTypeMapper.java
  src/main/java/com/kobylynskyi/graphql/codegen/scala/ScalaValueFormatter.java
  src/main/resources/templates/scala-lang/scalaClassGraphqlInterface.ftl
  src/main/resources/templates/scala-lang/scalaClassGraphqlOperations.ftl
  src/main/resources/templates/scala-lang/scalaClassGraphqlParametrizedInput.ftl
  src/main/resources/templates/scala-lang/scalaClassGraphqlRequest.ftl
  src/main/resources/templates/scala-lang/scalaClassGraphqlType.ftl
  src/test/resources/expected-classes/scala/AddLabelsToLabelableInput.scala.txt
  src/test/resources/expected-classes/scala/AddLabelsToLabelableMutationRequest.scala.txt
  src/test/resources/expected-classes/scala/AddLabelsToLabelablePayload.scala.txt
  src/test/resources/expected-classes/scala/CodesOfConductQueryResolver.scala.txt
  src/test/resources/expected-classes/scala/Commit.scala.txt
  src/test/resources/expected-classes/scala/Commit_Var_Field.scala.txt
  src/test/resources/expected-classes/scala/Commit_noValidationAnnotation.scala.txt
  src/test/resources/expected-classes/scala/Commit_no_final_class.scala.txt
  src/test/resources/expected-classes/scala/Commit_withPrimitives.scala.txt
  src/test/resources/expected-classes/scala/Commit_withoutPrimitives.scala.txt
  src/test/resources/expected-classes/scala/GithubAcceptTopicSuggestionInputTO.scala.txt
  src/test/resources/expected-classes/scala/GithubCommitTO.scala.txt
  src/test/resources/expected-classes/scala/QueryINeedQueryRequest.scala.txt
  src/test/resources/expected-classes/scala/QueryINeedQueryRequest_custom_serializer.scala.txt
  src/test/resources/expected-classes/scala/annotation/CreateEventMutationResolver.scala.txt
  src/test/resources/expected-classes/scala/annotation/MutationResolver.scala.txt
  src/test/resources/expected-classes/scala/builder/CaseQueryRequest.scala.txt
  src/test/resources/expected-classes/scala/custom-type/QueryINeedQueryRequest.scala.txt
  src/test/resources/expected-classes/scala/custom-type/QueryINeedQueryRequest_whole_scalar.scala.txt
  src/test/resources/expected-classes/scala/custom-type/ResponseContainingDate.scala.txt
  src/test/resources/expected-classes/scala/deprecated/EventsQueryResolver.scala.txt
  src/test/resources/expected-classes/scala/deprecated/QueryResolver.scala.txt
  src/test/resources/expected-classes/scala/extend/AssetsQueryResolver.scala.txt
  src/test/resources/expected-classes/scala/extend/Event.scala.txt
  src/test/resources/expected-classes/scala/extend/EventInput.scala.txt
  src/test/resources/expected-classes/scala/extend/EventsQueryResolver.scala.txt
  src/test/resources/expected-classes/scala/extend/QueryResolver.scala.txt
  src/test/resources/expected-classes/scala/extend/nullable/Event.scala.txt
  src/test/resources/expected-classes/scala/extend/nullable/Null1QueryQueryResolver.scala.txt
  src/test/resources/expected-classes/scala/extend/nullable/Null2QueryQueryResolver.scala.txt
  src/test/resources/expected-classes/scala/extend/nullable/Null3QueryQueryResolver.scala.txt
  src/test/resources/expected-classes/scala/extend/nullable/QueryResolver.scala.txt
  src/test/resources/expected-classes/scala/extend/nullreturn/SimpleEventCountsQueryResolver.scala.txt
  src/test/resources/expected-classes/scala/extend/nullreturn/SimplesQueryResolver.scala.txt
  src/test/resources/expected-classes/scala/extend/resolver/SimpleEventCountsQueryResolver.scala.txt
  src/test/resources/expected-classes/scala/extend/resolver/SimpleEventCountsQueryResponse.scala.txt
  src/test/resources/expected-classes/scala/optional/TypeWithMandatoryField.scala.txt
  src/test/resources/expected-classes/scala/relay/OrganizationsQueryResolver.scala.txt
  src/test/resources/expected-classes/scala/relay/QueryResolver.scala.txt
  src/test/resources/expected-classes/scala/tostring/QueryPrivateParametrizedInput.scala.txt
  src/test/resources/expected-classes/scala/tostring/Synchronized.scala.txt
  src/test/resources/expected-classes/scala/tostring/TOSTRING_Synchronized.scala.txt
Labels: bug, scala

#608 Support hocon config and list of config file
  build.gradle
  docs/codegen-options.md
  plugins/gradle/graphql-java-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphQLCodegenGradleTask.java
  plugins/maven/graphql-java-codegen-maven-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/GraphQLCodegenMojo.java
  plugins/sbt/graphql-java-codegen-sbt-plugin/src/main/scala/io/github/dreamylost/graphql/codegen/GraphQLCodegenKeys.scala
  plugins/sbt/graphql-java-codegen-sbt-plugin/src/main/scala/io/github/dreamylost/graphql/codegen/GraphQLCodegenPlugin.scala
  src/main/java/com/kobylynskyi/graphql/codegen/supplier/JsonMappingConfigSupplier.java
  src/main/java/com/kobylynskyi/graphql/codegen/supplier/MergeableMappingConfigSupplier.java
  src/main/java/com/kobylynskyi/graphql/codegen/utils/Utils.java
  src/test/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenExternalConfigTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/supplier/JsonMappingConfigSupplierTest.java
  src/test/java/com/kobylynskyi/graphql/codegen/supplier/MergeableMappingConfigSupplierTest.java
  src/test/resources/json/mappingconfig2.json
  src/test/resources/json/mappingconfig3.json
  src/test/resources/json/mappingconfig4.conf
  src/test/resources/json/mappingconfig5.conf
  src/test/resources/json/mappingconfig6.conf
Labels: breaking change

#615 Add migration guide for upcoming release 5.0.0 #585
  docs/migration-to-5.0.0.md
Labels: documentation
